version: 2.1

# this allows you to use CircleCI's dynamic configuration feature
setup: true

orbs:
  continuation: circleci/continuation@1.0.0
  path-filtering: circleci/path-filtering@1.0.0

parameters:
  check_files:
    type: boolean
    default: true
  run_all:
    type: boolean
    default: false

jobs:
  choose_ci_jobs:
    docker: # executor type
      - image: cimg/base:stable
    resource_class: small
    steps:
      - checkout
      - run:
          name: Create config
          command: |
            cat .circleci/configurations/top_level.yml > .circleci/generated_config.yml
            cat .circleci/configurations/executors.yml >> .circleci/generated_config.yml
            cat .circleci/configurations/commands.yml >> .circleci/generated_config.yml
            cat .circleci/configurations/jobs.yml >> .circleci/generated_config.yml
            cat .circleci/configurations/workflows.yml >> .circleci/generated_config.yml
      - run:
          name: Compute parameters
          command: |
            echo "Creating the pipeline parameters in /tmp/mapping_pipeline_params"
            echo "*/.* run_all true" > /tmp/mapping_pipeline_params
      - path-filtering/set-parameters:
          base-revision: main
          config-path: .circleci/generated_config.yml
          mapping: /tmp/mapping_pipeline_params
      # - when:
      #     condition:
      #       equal: [ << pipeline.parameters.run_all >>, true ]
      #     steps:
      #       - checkout
      #       - continuation/continue:
      #           configuration_path: .circleci/_config.yml
      # - when:
      #     condition:
      #       equal: [ << pipeline.parameters.check_files >>, true ]
      #     steps:
      #       - run:
      #           name: Check Files
      #           # TODO replace the CIRCLE_API_TOKEN with a machine user on monday
      #           command: |
      #             PR_NUMBER="${CI_PULL_REQUEST##*/}"
      #             echo $PR_NUMBER

      #             echo $CIRCLE_BRANCH
      #             echo "{ \"branch\": \"$CIRCLE_BRANCH\", \"parameters\": { \"check_files\": false, \"run_all\": true } }"

      #             curl -X POST https://circleci.com/api/v2/project/gh/facebook/react-native/pipeline \
      #               -H "Content-Type: application/json" \
      #               -H "Accept: application/json" \
      #               -H "Circle-Token: $CIRCLE_API_TOKEN" \
      #               -d "{ \"branch\": \"pull/$PR_NUMBER/head\", \"parameters\": { \"check_files\": false, \"run_all\": true } }"
      #       - continuation/finish




# our single workflow, that triggers the setup job defined above
workflows:
  always-run:
    jobs:
      - choose_ci_jobs
